### ISSUE TITLE
SINTESIS_ELEMENTOS IMPORTANTES DE LA GESTIÓN DE PROYECTOS DE SOFTWARE

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/actividad-3-sintesis-Rigoberto2001#2]
[SINTESIS_RIGOBERTORAMIREZNICOLAS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Rigoberto2001/files/9447468/SINTESIS_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by salathiel1999** [comment]
18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
